alpertuna/vim-header

autoload/header.vim

Add license header support for Haskell.

Add support for Haskell

---

README.md
autoload/header.vim

Add license header support for Lua. Also add Lua to the list of supported languages.

Add support for Lua

---

README.md
autoload/header.vim

Add license header support for Groovy and Sass files. Also add Groovy and Sass to the list of supported languages.

Add support for Groovy and Sass

---

autoload/header.vim

Every time I saved a file, I lost the current position in the buffer. This change keeps it (as close as possible).

Remembers last edit position and restores it.

---

autoload/header.vim

The first line if is already in the file, is no longer added. 
Before this change, each add_header and add_min_header and license added its own first line.
Also removed trailing white space (after infos) in license function.

First line is no longer added, if already exists.

---

CHANGELOG.md
README.md
autoload/header.vim

Minor changes to include matlab and octave as per #17   
Included the update information in the changelog and readme.

Added support for matlab/octave

---

CHANGELOG.md
README.md

This patch updates CHANGELOG and README to reflects changes introduced
by commit 199af95a.

filetype: cfg, update README and CHANGELOG

---

autoload/header.vim

Just threw in a few lines to give it basic functionality with .R files. Thanks so much for the useful plugin!

Added support for R files

---

autoload/header.vim

Change `#!/bin/bash` to `#!/bin/zsh` for zsh type files.

add support for zsh

---

README.md
licensefiles/wtfpl
plugin/header.vim

tell me if i need to fix something
thx

added wtfpl

---

README.md
licensefiles/agpl
plugin/header.vim

What the commit says. Nothing more, nothing less.

add AGPL as available license in code and documentation

---

autoload/header.vim

add-perl6-support

---

autoload/header.vim

comment_begin was misspelled as comment_start, comment_block was not set

Markdown support fixed

---

autoload/header.vim

Added few lines to support Makefile. Now autosave updates works properly.

Fix makefile

---

autoload/header.vim

add file types according to build-in versions https://github.com/vim/vim/issues/4830

add React related file types

---

autoload/header.vim

feat: Add support for DART

---

README.md
autoload/header.vim
plugin/header.vim

Add a option to only update the header.

add option g:header_auto_update_header

---

autoload/header.vim

- Added support for fish shell
- Added support for SQL scripts

Add supported for fish and sql

---

README.md
autoload/header.vim

I have added Svelte file type support.

add svelte file syntax support

---

README.md
autoload/header.vim

Hello,
This PR adds 2 custom variables to plugin:
- `g:header_field_project`
- `g:header_field_last_separator`
And also minor a modification to `b:field_timestamp` content from `"Date"` -> `"File Created"`
Feel free to comment/merge and/or reject it.
KR

Add fields Project/Separator
